name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure
